export const utlMetricDefinitions = [
  // 1. Traffic Metrics
  {
    metric_id: "users",
    name: "Total Active Users",
    description: "Total unique visitors across all UTL.tools pages per period",
    unit: "users",
    source_id: "SRC-GA4-UTL",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "CRITICAL",
  },
  {
    metric_id: "sessions",
    name: "Total Sessions",
    description: "Total browsing sessions on UTL.tools",
    unit: "sessions",
    source_id: "SRC-GA4-UTL",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "HIGH",
  },
  {
    metric_id: "engaged_sessions",
    name: "Engaged Sessions",
    description: "Sessions lasting longer than 10s or with 2+ page interactions",
    unit: "sessions",
    source_id: "SRC-GA4-UTL",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "HIGH",
  },
  {
    metric_id: "organic_users",
    name: "Organic Search Users",
    description: "Visitors arriving via Google/Bing search engines",
    unit: "users",
    source_id: "SRC-GA4-UTL",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "CRITICAL",
  },

  // 2. Search Console Metrics
  {
    metric_id: "search_impressions",
    name: "Google Search Impressions",
    description: "Number of times UTL pages appeared in Google organic search results",
    unit: "impressions",
    source_id: "SRC-GSC-UTL",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "CRITICAL",
  },
  {
    metric_id: "search_clicks",
    name: "Google Search Clicks",
    description: "Total clicks from Google organic search results to UTL.tools",
    unit: "clicks",
    source_id: "SRC-GSC-UTL",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "CRITICAL",
  },
  {
    metric_id: "search_ctr",
    name: "Search Click-Through Rate",
    description: "Percentage of impressions resulting in a click (Clicks / Impressions * 100)",
    unit: "percentage",
    source_id: "SRC-GSC-UTL",
    aggregation: "AVG",
    direction: "HIGHER_IS_BETTER",
    target_value: 4.5,
    importance: "HIGH",
  },
  {
    metric_id: "average_position",
    name: "Average Search Ranking Position",
    description: "Mean average ranking position of UTL URLs across all Google search queries",
    unit: "rank",
    source_id: "SRC-GSC-UTL",
    aggregation: "AVG",
    direction: "LOWER_IS_BETTER",
    target_value: 10.0,
    importance: "HIGH",
  },

  // 3. Utility Usage Metrics
  {
    metric_id: "utility_views",
    name: "Utility Page Views",
    description: "Total page loads across all 47 interactive web utilities",
    unit: "views",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "CRITICAL",
  },
  {
    metric_id: "utility_interactions",
    name: "Utility Tool Executions",
    description: "Successful client-side tool calculations and generator runs",
    unit: "actions",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "CRITICAL",
  },
  {
    metric_id: "utility_shares",
    name: "Tool Share Events",
    description: "Clicks on the native Web Share or 1-click URL copy buttons",
    unit: "shares",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "MEDIUM",
  },
  {
    metric_id: "utility_bookmarks",
    name: "Local Bookmarks Saved",
    description: "Tools saved to local browser favorites in localStorage",
    unit: "bookmarks",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "MEDIUM",
  },

  // 4. Windows Widget Discovery Metrics
  {
    metric_id: "widget_views",
    name: "Widget Hub & Item Views",
    description: "Total page views on /widgets hub, category pages, and item detail pages",
    unit: "views",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "HIGH",
  },
  {
    metric_id: "widget_searches",
    name: "Widget Search Queries",
    description: "Interactive searches performed inside the Windows Widget modal",
    unit: "searches",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "MEDIUM",
  },
  {
    metric_id: "widget_external_clicks",
    name: "Widget Official Installer Clicks",
    description: "Outbound navigation clicks to Microsoft Store, GitHub, or official site installers",
    unit: "clicks",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "HIGH",
  },
  {
    metric_id: "widget_related_utility_clicks",
    name: "Widget to Web Utility Clicks",
    description: "Cross-navigation clicks from desktop widget reviews to zero-install web tools",
    unit: "clicks",
    source_id: "SRC-UTL-TELEMETRY",
    aggregation: "SUM",
    direction: "HIGHER_IS_BETTER",
    importance: "HIGH",
  },
];
