"use client";

import React, { useState } from "react";
import { Terminal, Activity, Copy, Check, Server, Zap } from "lucide-react";

export function CronToPushgatewayConverter() {
  const [cronExpr, setCronExpr] = useState<string>("*/30 * * * *");
  const [jobName, setJobName] = useState<string>("db-vacuum-analyze");
  const [command, setCommand] = useState<string>("/usr/bin/psql -d analytics -c 'VACUUM ANALYZE;'");
  const [pushgatewayUrl, setPushgatewayUrl] = useState<string>("http://prometheus-pushgateway.monitoring.svc:9091");
  const [instanceLabel, setInstanceLabel] = useState<string>("prod-db-worker-01");
  const [useAuth, setUseAuth] = useState<boolean>(false);
  const [authTokenVar, setAuthTokenVar] = useState<string>("PUSHGATEWAY_AUTH_TOKEN");

  const [copiedScript, setCopiedScript] = useState(false);
  const [copiedCrontab, setCopiedCrontab] = useState(false);

  const scriptWrapper = `#!/usr/bin/env bash
# ==============================================================================
# Prometheus Pushgateway Exporter for Scheduled Cron Job: ${jobName}
# Generated by UTL.tools — Native curl metric push without Node/Python dependencies
# ==============================================================================
set -euo pipefail

JOB_NAME="${jobName}"
INSTANCE="\${INSTANCE_NAME:-${instanceLabel}}"
GATEWAY_URL="${pushgatewayUrl}"

START_TIME=$(date +%s)

# Execute scheduled job command
set +e
${command}
EXIT_CODE=$?
set -e

END_TIME=$(date +%s)
DURATION=$(( END_TIME - START_TIME ))

STATUS=0
[ $EXIT_CODE -eq 0 ] && STATUS=1

# Formulate Prometheus OpenMetrics payload
METRIC_PAYLOAD=$(cat <<EOF
# HELP cron_job_duration_seconds Total execution time of the scheduled job in seconds
# TYPE cron_job_duration_seconds gauge
cron_job_duration_seconds{job="$JOB_NAME",instance="$INSTANCE"} $DURATION

# HELP cron_job_last_exit_code Process exit code of the last cron execution
# TYPE cron_job_last_exit_code gauge
cron_job_last_exit_code{job="$JOB_NAME",instance="$INSTANCE"} $EXIT_CODE

# HELP cron_job_status Status flag of execution (1=success, 0=failure)
# TYPE cron_job_status gauge
cron_job_status{job="$JOB_NAME",instance="$INSTANCE"} $STATUS

$( [ $EXIT_CODE -eq 0 ] && echo "# HELP cron_job_last_success_timestamp_seconds Timestamp of last successful completion
# TYPE cron_job_last_success_timestamp_seconds gauge
cron_job_last_success_timestamp_seconds{job=\"$JOB_NAME\",instance=\"$INSTANCE\"} $END_TIME" )
EOF
)

# Push metrics to Prometheus Pushgateway
TARGET_URL="\${GATEWAY_URL}/metrics/job/\${JOB_NAME}/instance/\${INSTANCE}"

${useAuth ? `AUTH_HEADER="-H 'Authorization: Bearer \${${authTokenVar}:-}'"` : "AUTH_HEADER=\"\""}

echo "$METRIC_PAYLOAD" | curl -s --data-binary @- $AUTH_HEADER "$TARGET_URL" > /dev/null 2>&1 || true

exit $EXIT_CODE`;

  const crontabLine = `${cronExpr} /opt/cron-wrappers/${jobName}-wrapper.sh >> /var/log/${jobName}.log 2>&1`;

  const handleCopyScript = async () => {
    try {
      await navigator.clipboard.writeText(scriptWrapper);
      setCopiedScript(true);
      setTimeout(() => setCopiedScript(false), 2000);
    } catch {}
  };

  const handleCopyCrontab = async () => {
    try {
      await navigator.clipboard.writeText(crontabLine);
      setCopiedCrontab(true);
      setTimeout(() => setCopiedCrontab(false), 2000);
    } catch {}
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-slate-200">
      {/* Header */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-6 shadow-xl backdrop-blur-sm">
        <div className="flex items-center gap-2 mb-2">
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-500/10 text-rose-400 border border-rose-500/20">
            Prometheus & Grafana
          </span>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
            Pushgateway Batch Exporter
          </span>
        </div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <Zap className="w-6 h-6 text-rose-400" />
          Crontab to Prometheus Pushgateway Metric Exporter
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          Transform Linux cron jobs into Prometheus batch telemetry streams. Export duration gauges, exit codes, and last-success timestamps directly to Pushgateway or Grafana Cloud.
        </p>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Form (5 cols) */}
        <div className="lg:col-span-5 space-y-5">
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-4">
            <h3 className="text-sm font-semibold text-white">Target Job & Prometheus Metrics</h3>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Job Identifier Name</label>
              <input
                type="text"
                value={jobName}
                onChange={(e) => setJobName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-rose-400 font-mono focus:ring-1 focus:ring-rose-500 outline-none"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Command to Execute</label>
              <textarea
                value={command}
                onChange={(e) => setCommand(e.target.value)}
                rows={2}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-xs text-slate-200 font-mono focus:ring-1 focus:ring-rose-500 outline-none resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs text-slate-400 block mb-1">Cron Expression</label>
                <input
                  type="text"
                  value={cronExpr}
                  onChange={(e) => setCronExpr(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono"
                />
              </div>
              <div>
                <label className="text-xs text-slate-400 block mb-1">Instance Label</label>
                <input
                  type="text"
                  value={instanceLabel}
                  onChange={(e) => setInstanceLabel(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono"
                />
              </div>
            </div>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Pushgateway URL</label>
              <input
                type="text"
                value={pushgatewayUrl}
                onChange={(e) => setPushgatewayUrl(e.target.value)}
                placeholder="http://pushgateway:9091"
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-indigo-300 font-mono"
              />
            </div>

            <div className="pt-2 border-t border-slate-800">
              <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={useAuth}
                  onChange={(e) => setUseAuth(e.target.checked)}
                  className="rounded border-slate-700 bg-slate-800 text-rose-500 focus:ring-0"
                />
                <span>Add Bearer Authentication Header</span>
              </label>
              {useAuth && (
                <div className="mt-2">
                  <label className="text-[11px] text-slate-400 block mb-1">Env Var Name for Token</label>
                  <input
                    type="text"
                    value={authTokenVar}
                    onChange={(e) => setAuthTokenVar(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded px-2 py-1 text-xs font-mono text-slate-300"
                  />
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right Code Outputs (7 cols) */}
        <div className="lg:col-span-7 space-y-5">
          {/* Shell Script */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <Terminal className="w-4 h-4 text-rose-400" /> Standalone Bash Wrapper Script
              </span>
              <button
                onClick={handleCopyScript}
                className="px-2.5 py-1 bg-rose-600 hover:bg-rose-500 text-white text-xs font-semibold rounded flex items-center gap-1 transition shadow-sm"
              >
                {copiedScript ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedScript ? "Copied!" : "Copy Script"}
              </button>
            </div>
            <pre className="w-full bg-slate-950/90 font-mono text-xs text-rose-300/90 border border-slate-800 rounded-xl p-4 overflow-x-auto max-h-[300px] leading-relaxed shadow-inner">
              <code>{scriptWrapper}</code>
            </pre>
          </div>

          {/* Crontab Line */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300">Crontab Entry</span>
              <button
                onClick={handleCopyCrontab}
                className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium rounded border border-slate-700 transition"
              >
                {copiedCrontab ? "Copied!" : "Copy Entry"}
              </button>
            </div>
            <pre className="w-full bg-slate-950/90 font-mono text-xs text-slate-200 border border-slate-800 rounded-xl p-3 overflow-x-auto leading-relaxed">
              <code>{crontabLine}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CronToPushgatewayConverter;
