"use client";

import React, { useState } from "react";
import { Terminal, Activity, Copy, Check, ShieldAlert, Zap } from "lucide-react";

export function CronToOpsgenieConverter() {
  const [cronExpr, setCronExpr] = useState<string>("0 4 * * *");
  const [jobName, setJobName] = useState<string>("db-backup-s3");
  const [command, setCommand] = useState<string>("/usr/local/bin/pg_dumpall | gzip | aws s3 cp - s3://backups/db.sql.gz");
  const [apiKeyVar, setApiKeyVar] = useState<string>("OPSGENIE_API_KEY");
  const [region, setRegion] = useState<"US" | "EU">("US");
  const [alertPriority, setAlertPriority] = useState<string>("P2");

  const [copiedScript, setCopiedScript] = useState(false);
  const [copiedCrontab, setCopiedCrontab] = useState(false);

  const apiHost = region === "EU" ? "api.eu.opsgenie.com" : "api.opsgenie.com";

  const scriptWrapper = `#!/usr/bin/env bash
# ==============================================================================
# Atlassian Opsgenie Heartbeat & Failure Alert Wrapper for: ${jobName}
# Generated by UTL.tools — Native curl heartbeat ping & automated alert triage
# ==============================================================================
set -euo pipefail

JOB_NAME="${jobName}"
API_KEY="\${${apiKeyVar}:-}"
API_HOST="${apiHost}"

if [ -z "$API_KEY" ]; then
  echo "[WARN] $API_KEY not set. Executing job without Opsgenie telemetry..." >&2
  exec ${command}
fi

START_TS=$(date +%s)
LOG_FILE="/tmp/\${JOB_NAME}_exec.log"

# Execute scheduled command, capturing combined output
set +e
(${command}) > "$LOG_FILE" 2>&1
EXIT_CODE=$?
set -e

END_TS=$(date +%s)
DURATION=$(( END_TS - START_TS ))

if [ $EXIT_CODE -eq 0 ]; then
  # 1. Successful run -> Ping Opsgenie Heartbeat
  curl -s -X POST "https://$API_HOST/v2/heartbeats/$JOB_NAME/ping" \\
    -H "Authorization: GenieKey $API_KEY" \\
    -H "Content-Type: application/json" > /dev/null 2>&1 || true
else
  # 2. Failed run -> Trigger Opsgenie Critical Alert
  ERROR_SNIPPET=$(tail -n 25 "$LOG_FILE" | tr '"' "'" | tr '\\n' ' ')
  
  ALERT_PAYLOAD=$(cat <<EOF
{
  "message": "Cron Job Failure: $JOB_NAME exited with code $EXIT_CODE",
  "alias": "cron-fail-$JOB_NAME",
  "description": "Job failed after $DURATION seconds on host $(hostname). Error log snippet: $ERROR_SNIPPET",
  "priority": "${alertPriority}",
  "tags": ["cron", "scheduler", "automated-alert"]
}
EOF
)

  curl -s -X POST "https://$API_HOST/v2/alerts" \\
    -H "Authorization: GenieKey $API_KEY" \\
    -H "Content-Type: application/json" \\
    -d "$ALERT_PAYLOAD" > /dev/null 2>&1 || true
fi

# Cleanup
rm -f "$LOG_FILE"
exit $EXIT_CODE`;

  const crontabLine = `${cronExpr} /opt/cron-wrappers/${jobName}-wrapper.sh >> /var/log/${jobName}.log 2>&1`;

  const handleCopyScript = async () => {
    try {
      await navigator.clipboard.writeText(scriptWrapper);
      setCopiedScript(true);
      setTimeout(() => setCopiedScript(false), 2000);
    } catch {}
  };

  const handleCopyCrontab = async () => {
    try {
      await navigator.clipboard.writeText(crontabLine);
      setCopiedCrontab(true);
      setTimeout(() => setCopiedCrontab(false), 2000);
    } catch {}
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-slate-200">
      {/* Header */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-6 shadow-xl backdrop-blur-sm">
        <div className="flex items-center gap-2 mb-2">
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
            Atlassian Opsgenie
          </span>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-500/10 text-rose-400 border border-rose-500/20">
            Heartbeat & P1/P2 Alerting
          </span>
        </div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <Zap className="w-6 h-6 text-indigo-400" />
          Crontab to Opsgenie Heartbeat & Alert Telemetry Converter
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          Wrap scheduled Linux cron jobs into Opsgenie dead-man&apos;s snitches with automatic heartbeat pings on success and immediate incident alert dispatch on failure.
        </p>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Form (5 cols) */}
        <div className="lg:col-span-5 space-y-5">
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-4">
            <h3 className="text-sm font-semibold text-white">Target Job & Opsgenie Account</h3>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Opsgenie Heartbeat Name</label>
              <input
                type="text"
                value={jobName}
                onChange={(e) => setJobName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-indigo-400 font-mono focus:ring-1 focus:ring-indigo-500 outline-none"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Bash Command to Execute</label>
              <textarea
                value={command}
                onChange={(e) => setCommand(e.target.value)}
                rows={2}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-xs text-slate-200 font-mono focus:ring-1 focus:ring-indigo-500 outline-none resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs text-slate-400 block mb-1">Cron Expression</label>
                <input
                  type="text"
                  value={cronExpr}
                  onChange={(e) => setCronExpr(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono"
                />
              </div>
              <div>
                <label className="text-xs text-slate-400 block mb-1">Opsgenie Region</label>
                <select
                  value={region}
                  onChange={(e) => setRegion(e.target.value as "US" | "EU")}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 focus:ring-1 focus:ring-indigo-500 outline-none"
                >
                  <option value="US">US (api.opsgenie.com)</option>
                  <option value="EU">EU (api.eu.opsgenie.com)</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs text-slate-400 block mb-1">API Key Env Var</label>
                <input
                  type="text"
                  value={apiKeyVar}
                  onChange={(e) => setApiKeyVar(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono"
                />
              </div>
              <div>
                <label className="text-xs text-slate-400 block mb-1">Incident Priority</label>
                <select
                  value={alertPriority}
                  onChange={(e) => setAlertPriority(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 focus:ring-1 focus:ring-indigo-500 outline-none"
                >
                  <option value="P1">P1 (Critical Blocker)</option>
                  <option value="P2">P2 (High Priority)</option>
                  <option value="P3">P3 (Moderate Alert)</option>
                  <option value="P4">P4 (Low)</option>
                </select>
              </div>
            </div>
          </div>
        </div>

        {/* Right Code Outputs (7 cols) */}
        <div className="lg:col-span-7 space-y-5">
          {/* Shell Script */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <Terminal className="w-4 h-4 text-indigo-400" /> Standalone Bash Wrapper Script
              </span>
              <button
                onClick={handleCopyScript}
                className="px-2.5 py-1 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded flex items-center gap-1 transition shadow-sm"
              >
                {copiedScript ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedScript ? "Copied!" : "Copy Script"}
              </button>
            </div>
            <pre className="w-full bg-slate-950/90 font-mono text-xs text-indigo-300/90 border border-slate-800 rounded-xl p-4 overflow-x-auto max-h-[300px] leading-relaxed shadow-inner">
              <code>{scriptWrapper}</code>
            </pre>
          </div>

          {/* Crontab Line */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300">Crontab Entry</span>
              <button
                onClick={handleCopyCrontab}
                className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium rounded border border-slate-700 transition"
              >
                {copiedCrontab ? "Copied!" : "Copy Entry"}
              </button>
            </div>
            <pre className="w-full bg-slate-950/90 font-mono text-xs text-slate-200 border border-slate-800 rounded-xl p-3 overflow-x-auto leading-relaxed">
              <code>{crontabLine}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CronToOpsgenieConverter;
