"use client";

import React, { useState, useId } from "react";
import { Terminal, Activity, Copy, Check, ShieldCheck, Zap } from "lucide-react";

export function CronToHoneycombConverter() {
  const [cronExpr, setCronExpr] = useState<string>("0 3 * * *");
  const [command, setCommand] = useState<string>("/usr/local/bin/sync-stripe-invoices.sh --batch-size 500");
  const [jobName, setJobName] = useState<string>("sync-stripe-invoices");
  const [dataset, setDataset] = useState<string>("cron-jobs");
  const [apiKeyVar, setApiKeyVar] = useState<string>("HONEYCOMB_API_KEY");
  const [environment, setEnvironment] = useState<string>("production");
  const [createMarkerOnFailure, setCreateMarkerOnFailure] = useState<boolean>(true);

  const [copiedScript, setCopiedScript] = useState(false);
  const [copiedCrontab, setCopiedCrontab] = useState(false);

  const scriptWrapper = `#!/usr/bin/env bash
# ==============================================================================
# Honeycomb Telemetry Wrapper for Scheduled Cron Job: ${jobName}
# Generated by UTL.tools — Zero-agent, direct Honeycomb API instrumentation
# ==============================================================================
set -euo pipefail

JOB_NAME="${jobName}"
DATASET="${dataset}"
API_KEY="\${${apiKeyVar}:-}"
ENV="${environment}"
HOSTNAME="$(hostname -s 2>/dev/null || echo 'unknown-host')"

if [ -z "$API_KEY" ]; then
  echo "[WARN] $API_KEY is not set. Executing job without Honeycomb telemetry..." >&2
  exec ${command}
fi

START_TS=$(date +%s%N 2>/dev/null || date +%s)
START_EPOCH=$(date +%s)

# Execute job command
set +e
${command}
EXIT_CODE=$?
set -e

END_TS=$(date +%s%N 2>/dev/null || date +%s)
# Calculate elapsed duration in milliseconds
if [ "$START_TS" != "$START_EPOCH" ]; then
  DURATION_MS=$(( (END_TS - START_TS) / 1000000 ))
else
  DURATION_MS=$(( (END_TS - START_TS) * 1000 ))
fi

STATUS="success"
[ $EXIT_CODE -ne 0 ] && STATUS="failure"

# 1. Send Detailed Structured Event to Honeycomb
EVENT_PAYLOAD=$(cat <<EOF
{
  "name": "$JOB_NAME",
  "service.name": "cron-scheduler",
  "cron.expression": "${cronExpr}",
  "environment": "$ENV",
  "host.name": "$HOSTNAME",
  "duration_ms": $DURATION_MS,
  "exit_code": $EXIT_CODE,
  "status": "$STATUS",
  "success": $( [ $EXIT_CODE -eq 0 ] && echo "true" || echo "false" )
}
EOF
)

curl -s -X POST "https://api.honeycomb.io/1/events/$DATASET" \\
  -H "X-Honeycomb-Team: $API_KEY" \\
  -H "Content-Type: application/json" \\
  -d "$EVENT_PAYLOAD" > /dev/null 2>&1 || true

${createMarkerOnFailure ? `# 2. Emit Honeycomb Timeline Marker on Failure
if [ $EXIT_CODE -ne 0 ]; then
  MARKER_PAYLOAD=$(cat <<EOF
{
  "message": "Cron $JOB_NAME failed with exit code $EXIT_CODE",
  "type": "cron-failure",
  "url": ""
}
EOF
)
  curl -s -X POST "https://api.honeycomb.io/1/markers/$DATASET" \\
    -H "X-Honeycomb-Team: $API_KEY" \\
    -H "Content-Type: application/json" \\
    -d "$MARKER_PAYLOAD" > /dev/null 2>&1 || true
fi` : ""}

exit $EXIT_CODE`;

  const crontabLine = `${cronExpr} /opt/cron-wrappers/${jobName}-wrapper.sh >> /var/log/${jobName}.log 2>&1`;

  const handleCopyScript = async () => {
    try {
      await navigator.clipboard.writeText(scriptWrapper);
      setCopiedScript(true);
      setTimeout(() => setCopiedScript(false), 2000);
    } catch {}
  };

  const handleCopyCrontab = async () => {
    try {
      await navigator.clipboard.writeText(crontabLine);
      setCopiedCrontab(true);
      setTimeout(() => setCopiedCrontab(false), 2000);
    } catch {}
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-slate-200">
      {/* Header */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-6 shadow-xl backdrop-blur-sm">
        <div className="flex items-center gap-2 mb-2">
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/20">
            Observability & Telemetry
          </span>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
            Honeycomb /1/events & /1/markers
          </span>
        </div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <Zap className="w-6 h-6 text-amber-400" />
          Crontab to Honeycomb Marker & Metric Telemetry Converter
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          Wrap ordinary Linux cron jobs into high-cardinality Honeycomb telemetry events and timeline markers with automated runtime duration gauging and failure detection.
        </p>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Configuration Form (5 cols) */}
        <div className="lg:col-span-5 space-y-5">
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-4">
            <h3 className="text-sm font-semibold text-white">Cron & Honeycomb Metadata</h3>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Job Identifier Name</label>
              <input
                type="text"
                value={jobName}
                onChange={(e) => setJobName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-amber-400 font-mono focus:ring-1 focus:ring-amber-500 outline-none"
              />
            </div>

            <div>
              <label className="text-xs text-slate-400 block mb-1">Target Bash Command</label>
              <textarea
                value={command}
                onChange={(e) => setCommand(e.target.value)}
                rows={2}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-xs text-slate-200 font-mono focus:ring-1 focus:ring-amber-500 outline-none resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs text-slate-400 block mb-1">Cron Expression</label>
                <input
                  type="text"
                  value={cronExpr}
                  onChange={(e) => setCronExpr(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono focus:ring-1 focus:ring-amber-500 outline-none"
                />
              </div>
              <div>
                <label className="text-xs text-slate-400 block mb-1">Environment</label>
                <select
                  value={environment}
                  onChange={(e) => setEnvironment(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 focus:ring-1 focus:ring-amber-500 outline-none"
                >
                  <option value="production">production</option>
                  <option value="staging">staging</option>
                  <option value="development">development</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs text-slate-400 block mb-1">Honeycomb Dataset</label>
                <input
                  type="text"
                  value={dataset}
                  onChange={(e) => setDataset(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono focus:ring-1 focus:ring-amber-500 outline-none"
                />
              </div>
              <div>
                <label className="text-xs text-slate-400 block mb-1">API Key Env Var</label>
                <input
                  type="text"
                  value={apiKeyVar}
                  onChange={(e) => setApiKeyVar(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 font-mono focus:ring-1 focus:ring-amber-500 outline-none"
                />
              </div>
            </div>

            <div className="pt-2 border-t border-slate-800">
              <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={createMarkerOnFailure}
                  onChange={(e) => setCreateMarkerOnFailure(e.target.checked)}
                  className="rounded border-slate-700 bg-slate-800 text-amber-500 focus:ring-0"
                />
                <span>Create Honeycomb Timeline Marker on Non-Zero Exit</span>
              </label>
            </div>
          </div>
        </div>

        {/* Right: Code Outputs (7 cols) */}
        <div className="lg:col-span-7 space-y-5">
          {/* Shell Script */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <Terminal className="w-4 h-4 text-amber-400" /> Standalone Bash Wrapper Script
              </span>
              <button
                onClick={handleCopyScript}
                className="px-2.5 py-1 bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold rounded flex items-center gap-1 transition shadow-sm"
              >
                {copiedScript ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedScript ? "Copied!" : "Copy Script"}
              </button>
            </div>
            <pre className="w-full bg-slate-950/90 font-mono text-xs text-amber-300/90 border border-slate-800 rounded-xl p-4 overflow-x-auto max-h-[300px] leading-relaxed shadow-inner">
              <code>{scriptWrapper}</code>
            </pre>
          </div>

          {/* Crontab Line */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300">Crontab Entry</span>
              <button
                onClick={handleCopyCrontab}
                className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium rounded border border-slate-700 transition"
              >
                {copiedCrontab ? "Copied!" : "Copy Entry"}
              </button>
            </div>
            <pre className="w-full bg-slate-950/90 font-mono text-xs text-slate-200 border border-slate-800 rounded-xl p-3 overflow-x-auto leading-relaxed">
              <code>{crontabLine}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CronToHoneycombConverter;
