"use client";

import { useState, useMemo } from "react";
import { Database, Copy, Check, Sparkles, Table } from "lucide-react";
import { copyToClipboard } from "@/lib/utils";

const SAMPLE_CSV = `id,name,email,score,is_active
1,Alice Johnson,alice@example.com,94.5,true
2,Bob Smith,bob@example.com,88.0,false
3,Charlie Brown,charlie@example.com,91.2,true
4,Diana Prince,diana@example.com,98.7,true`;

export function CsvToSqliteConverter() {
  const [csvInput, setCsvInput] = useState<string>(SAMPLE_CSV);
  const [tableName, setTableName] = useState<string>("users");
  const [sqlDialect, setSqlDialect] = useState<"sqlite" | "postgres" | "mysql">("sqlite");
  const [copied, setCopied] = useState<boolean>(false);

  const { ddlSql, rowCount, columnCount } = useMemo(() => {
    if (!csvInput.trim()) return { ddlSql: "-- Paste CSV data above to generate SQL DDL", rowCount: 0, columnCount: 0 };

    const lines = csvInput.trim().split("\n").filter((l) => l.trim().length > 0);
    if (lines.length === 0) return { ddlSql: "-- Invalid CSV format", rowCount: 0, columnCount: 0 };

    const headers = lines[0].split(",").map((h) => h.trim().replace(/['"]/g, "").replace(/\s+/g, "_").toLowerCase());
    const dataRows = lines.slice(1).map((line) => line.split(",").map((cell) => cell.trim().replace(/^["']|["']$/g, "")));

    // Infer column types
    const colTypes = headers.map((header, idx) => {
      let isInt = true;
      let isFloat = true;
      let isBool = true;

      for (const row of dataRows) {
        const val = row[idx];
        if (!val) continue;

        if (isNaN(Number(val))) {
          isInt = false;
          isFloat = false;
        } else if (!Number.isInteger(Number(val))) {
          isInt = false;
        }

        if (val.toLowerCase() !== "true" && val.toLowerCase() !== "false" && val !== "1" && val !== "0") {
          isBool = false;
        }
      }

      if (isInt) return sqlDialect === "postgres" ? "INTEGER" : "INTEGER";
      if (isFloat) return sqlDialect === "postgres" ? "DOUBLE PRECISION" : sqlDialect === "mysql" ? "DOUBLE" : "REAL";
      if (isBool) return sqlDialect === "sqlite" ? "INTEGER" : "BOOLEAN";
      return sqlDialect === "postgres" ? "VARCHAR(255)" : sqlDialect === "mysql" ? "VARCHAR(255)" : "TEXT";
    });

    const safeTable = tableName.trim().replace(/\s+/g, "_") || "records";

    let sql = `-- ${sqlDialect.toUpperCase()} Schema & Batch Insertion generated by UTL.tools\n\n`;
    sql += `CREATE TABLE ${safeTable} (\n`;
    sql += headers.map((h, i) => `  ${h} ${colTypes[i]}`).join(",\n");
    sql += `\n);\n\n`;

    if (dataRows.length > 0) {
      sql += `INSERT INTO ${safeTable} (${headers.join(", ")}) VALUES\n`;
      const valuesList = dataRows.map((row) => {
        const formatted = row.map((cell, idx) => {
          const type = colTypes[idx];
          if (!cell) return "NULL";
          if (type.includes("INT") || type.includes("REAL") || type.includes("DOUBLE")) {
            return isNaN(Number(cell)) ? `'${cell.replace(/'/g, "''")}'` : cell;
          }
          return `'${cell.replace(/'/g, "''")}'`;
        });
        return `  (${formatted.join(", ")})`;
      });
      sql += valuesList.join(",\n") + `;\n`;
    }

    return {
      ddlSql: sql,
      rowCount: dataRows.length,
      columnCount: headers.length,
    };
  }, [csvInput, tableName, sqlDialect]);

  const handleCopy = async () => {
    const ok = await copyToClipboard(ddlSql);
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-6">
      {/* Parameters */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="p-4 bg-card border border-border rounded-xl space-y-2">
          <label className="text-xs font-semibold text-foreground uppercase tracking-wider block">
            Target Table Name
          </label>
          <input
            type="text"
            value={tableName}
            onChange={(e) => setTableName(e.target.value)}
            placeholder="users"
            className="w-full px-3 py-2 text-sm font-mono font-bold bg-background border border-border rounded-lg text-foreground"
          />
        </div>

        <div className="p-4 bg-card border border-border rounded-xl space-y-2">
          <label className="text-xs font-semibold text-foreground uppercase tracking-wider block">
            SQL Target Dialect
          </label>
          <select
            value={sqlDialect}
            onChange={(e) => setSqlDialect(e.target.value as any)}
            className="w-full px-3 py-2 text-xs font-bold bg-background border border-border rounded-lg text-foreground"
          >
            <option value="sqlite">SQLite (TEXT, INTEGER, REAL)</option>
            <option value="postgres">PostgreSQL (VARCHAR, DOUBLE PRECISION)</option>
            <option value="mysql">MySQL (VARCHAR, DOUBLE)</option>
          </select>
        </div>
      </div>

      {/* CSV Input */}
      <div className="p-4 bg-card border border-border rounded-xl space-y-2">
        <div className="flex justify-between items-center text-xs text-muted-foreground">
          <label className="font-semibold uppercase text-foreground">Paste CSV Data</label>
          <span className="font-mono">
            {columnCount} cols × {rowCount} rows detected
          </span>
        </div>
        <textarea
          value={csvInput}
          onChange={(e) => setCsvInput(e.target.value)}
          rows={6}
          placeholder="id,name,email..."
          className="w-full px-3 py-2 text-xs font-mono bg-background border border-border rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {/* Generated SQL DDL */}
      <div className="p-5 bg-muted/30 border border-border rounded-xl space-y-3">
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-bold text-foreground flex items-center gap-1.5">
            <Database className="w-4 h-4 text-emerald-500" />
            Generated SQL Schema &amp; Batch INSERT DDL
          </h4>
          <button
            onClick={handleCopy}
            className="text-xs text-blue-600 dark:text-blue-400 font-semibold hover:underline inline-flex items-center gap-1"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? "Copied!" : "Copy SQL DDL"}</span>
          </button>
        </div>

        <pre className="p-4 bg-card border border-border rounded-xl font-mono text-xs text-emerald-600 dark:text-emerald-400 overflow-x-auto select-all max-h-80">
          {ddlSql}
        </pre>
      </div>
    </div>
  );
}
