"use client";

import React, { useState, useId } from "react";
import { Copy, Check, Terminal, Code2, Sparkles, RefreshCw } from "lucide-react";

interface ParsedCurl {
  method: string;
  url: string;
  headers: Record<string, string>;
  data?: string;
  hasAuth: boolean;
  authHeader?: string;
}

const SAMPLE_CURLS = [
  {
    name: "POST JSON with Bearer Token",
    command: `curl -X POST "https://api.sendgrid.com/v3/mail/send" \\
  -H "Authorization: Bearer SG.live_key_88921" \\
  -H "Content-Type: application/json" \\
  -d '{"personalizations":[{"to":[{"email":"dev@corp.net"}]}],"from":{"email":"ops@company.io"},"subject":"Deployment Succeeded"}'`
  },
  {
    name: "GET with Custom Headers & Query",
    command: `curl -X GET "https://api.github.com/orgs/utility-os/repos?per_page=50" \\
  -H "Accept: application/vnd.github+json" \\
  -H "User-Agent: Java-HttpClient/21"`
  },
  {
    name: "PUT with Basic Auth",
    command: `curl -X PUT "https://service.internal/v1/clusters/c-99/config" \\
  -u "admin:SecretPass99" \\
  -H "Content-Type: application/json" \\
  -d '{"replicaCount":5,"autoscaling":true}'`
  }
];

export function CurlToJavaHttpClientConverter() {
  const inputId = useId();
  const [curlInput, setCurlInput] = useState(SAMPLE_CURLS[0].command);
  const [useAsync, setUseAsync] = useState(false);
  const [generateRecord, setGenerateRecord] = useState(true);
  const [copied, setCopied] = useState(false);

  // Parse cURL
  const parseCurl = (cmd: string): ParsedCurl => {
    let method = "GET";
    let url = "";
    const headers: Record<string, string> = {};
    let data: string | undefined = undefined;
    let hasAuth = false;
    let authHeader: string | undefined = undefined;

    const cleanCmd = cmd.replace(/\\\r?\n/g, " ").trim();

    const urlMatch = cleanCmd.match(/(?:https?:\/\/[^\s"']+)/i);
    if (urlMatch) {
      url = urlMatch[0].replace(/["']/g, "");
    }

    const methodMatch = cleanCmd.match(/(?:-X|--request)\s+([A-Z]+)/i);
    if (methodMatch) {
      method = methodMatch[1].toUpperCase();
    } else if (cleanCmd.includes("-d ") || cleanCmd.includes("--data ") || cleanCmd.includes("--data-raw ")) {
      method = "POST";
    }

    const headerRegex = /(?:-H|--header)\s+["']([^"']+)["']/gi;
    let hMatch: RegExpExecArray | null;
    while ((hMatch = headerRegex.exec(cleanCmd)) !== null) {
      const parts = hMatch[1].split(/:\s*/);
      if (parts.length >= 2) {
        const key = parts[0].trim();
        const val = parts.slice(1).join(":").trim();
        headers[key] = val;
        if (key.toLowerCase() === "authorization") {
          hasAuth = true;
          authHeader = val;
        }
      }
    }

    const userMatch = cleanCmd.match(/(?:-u|--user)\s+["']?([^"'\s]+)["']?/i);
    if (userMatch && !hasAuth) {
      hasAuth = true;
      try {
        const b64 = typeof window !== "undefined" ? btoa(userMatch[1]) : Buffer.from(userMatch[1]).toString("base64");
        authHeader = `Basic ${b64}`;
        headers["Authorization"] = authHeader;
      } catch {
        authHeader = "Basic <BASE64>";
        headers["Authorization"] = authHeader;
      }
    }

    const dataMatch = cleanCmd.match(/(?:-d|--data|--data-raw)\s+['"]([^'"]+)['"]/i) ||
                      cleanCmd.match(/(?:-d|--data|--data-raw)\s+([^\s]+)/i);
    if (dataMatch) {
      data = dataMatch[1];
    }

    return { method, url: url || "https://api.example.com/endpoint", headers, data, hasAuth, authHeader };
  };

  const parsed = parseCurl(curlInput);

  // Generate Java Code
  const generateJava = (): string => {
    const lines: string[] = [];
    lines.push("// Generated by UTL.tools — cURL to Java Modern HttpClient Converter");
    lines.push("// Standard Java 11 / 17 / 21 library; zero external dependencies required");
    lines.push("package com.example.client;");
    lines.push("");
    lines.push("import java.io.IOException;");
    lines.push("import java.net.URI;");
    lines.push("import java.net.http.HttpClient;");
    lines.push("import java.net.http.HttpRequest;");
    lines.push("import java.net.http.HttpResponse;");
    lines.push("import java.time.Duration;");
    if (useAsync) {
      lines.push("import java.util.concurrent.CompletableFuture;");
    }
    lines.push("");
    lines.push("public class ApiClient {");
    lines.push("    private static final HttpClient client = HttpClient.newBuilder()");
    lines.push("            .version(HttpClient.Version.HTTP_2)");
    lines.push("            .connectTimeout(Duration.ofSeconds(15))");
    lines.push("            .build();");
    lines.push("");

    if (useAsync) {
      lines.push("    public static CompletableFuture<String> executeRequestAsync() {");
    } else {
      lines.push("    public static String executeRequest() throws IOException, InterruptedException {");
    }

    // Body publisher
    let bodyPublisher = "HttpRequest.BodyPublishers.noBody()";
    if (parsed.data) {
      lines.push("        String jsonPayload = \"\"\"");
      try {
        const pretty = JSON.stringify(JSON.parse(parsed.data), null, 4);
        lines.push(pretty);
      } catch {
        lines.push(parsed.data);
      }
      lines.push("        \"\"\";");
      bodyPublisher = "HttpRequest.BodyPublishers.ofString(jsonPayload)";
    }

    lines.push("");
    lines.push("        HttpRequest.Builder requestBuilder = HttpRequest.newBuilder()");
    lines.push(`                .uri(URI.create("${parsed.url}"))`);
    lines.push("                .timeout(Duration.ofSeconds(30))");

    // Method and publisher
    if (parsed.method === "GET") {
      lines.push("                .GET()");
    } else if (parsed.method === "DELETE") {
      lines.push("                .DELETE()");
    } else if (parsed.method === "POST") {
      lines.push(`                .POST(${bodyPublisher})`);
    } else if (parsed.method === "PUT") {
      lines.push(`                .PUT(${bodyPublisher})`);
    } else {
      lines.push(`                .method("${parsed.method}", ${bodyPublisher})`);
    }

    // Headers
    for (const [k, v] of Object.entries(parsed.headers)) {
      lines.push(`                .header("${k}", "${v.replace(/"/g, '\\"')}")`);
    }

    lines.push("                ;");
    lines.push("");
    lines.push("        HttpRequest request = requestBuilder.build();");
    lines.push("");

    if (useAsync) {
      lines.push("        return client.sendAsync(request, HttpResponse.BodyHandlers.ofString())");
      lines.push("                .thenApply(response -> {");
      lines.push("                    if (response.statusCode() >= 400) {");
      lines.push("                        throw new RuntimeException(\"HTTP Error: \" + response.statusCode());");
      lines.push("                    }");
      lines.push("                    return response.body();");
      lines.push("                });");
    } else {
      lines.push("        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());");
      lines.push("        if (response.statusCode() >= 400) {");
      lines.push("            throw new IOException(\"HTTP Request failed with status code: \" + response.statusCode());");
      lines.push("        }");
      lines.push("        return response.body();");
    }

    lines.push("    }");
    lines.push("}");

    // Record model
    if (generateRecord && parsed.data) {
      try {
        const json = JSON.parse(parsed.data);
        if (typeof json === "object" && json !== null && !Array.isArray(json)) {
          lines.push("");
          lines.push("// Suggested Java 14+ Record for this JSON payload:");
          lines.push("public record RequestPayload(");
          const entries = Object.entries(json);
          entries.forEach(([key, val], idx) => {
            let typeStr = "String";
            if (typeof val === "number") typeStr = Number.isInteger(val) ? "int" : "double";
            else if (typeof val === "boolean") typeStr = "boolean";
            else if (Array.isArray(val)) typeStr = "java.util.List<Object>";
            else if (typeof val === "object") typeStr = "Object";

            const comma = idx === entries.length - 1 ? "" : ",";
            lines.push(`    ${typeStr} ${key}${comma}`);
          });
          lines.push(") {}");
        }
      } catch {}
    }

    return lines.join("\n");
  };

  const javaCode = generateJava();

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(javaCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-slate-200">
      {/* Header */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-6 shadow-xl backdrop-blur-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-500/10 text-rose-400 border border-rose-500/20">
                Java 11 / 17 / 21 Standard Library
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                Zero-Dependency java.net.http
              </span>
            </div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              <Terminal className="w-6 h-6 text-rose-400" />
              cURL to Java Modern HttpClient Converter
            </h1>
            <p className="text-slate-400 text-sm mt-1">
              Transform raw cURL CLI commands into clean Java 11+ <code className="text-rose-300">java.net.http.HttpClient</code> code with synchronous or async <code className="text-rose-300">CompletableFuture</code> execution and typed Java records.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            {SAMPLE_CURLS.map((sample, idx) => (
              <button
                key={idx}
                onClick={() => setCurlInput(sample.command)}
                className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-xs font-medium text-slate-300 rounded-lg border border-slate-700 transition"
              >
                {sample.name}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: cURL Input */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label htmlFor={inputId} className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-rose-400" /> Input cURL Command
            </label>
            <button
              onClick={() => setCurlInput("")}
              className="text-xs text-slate-400 hover:text-slate-200 flex items-center gap-1 transition"
            >
              <RefreshCw className="w-3 h-3" /> Clear
            </button>
          </div>
          <textarea
            id={inputId}
            value={curlInput}
            onChange={(e) => setCurlInput(e.target.value)}
            rows={14}
            className="w-full bg-slate-950/90 font-mono text-xs text-rose-300 border border-slate-800 rounded-xl p-4 focus:ring-2 focus:ring-rose-500/40 focus:border-rose-500/50 outline-none resize-y leading-relaxed shadow-inner"
          />

          <div className="bg-slate-900/60 border border-slate-800/80 rounded-xl p-4 text-xs space-y-2">
            <div className="text-slate-400 font-semibold text-[11px] uppercase tracking-wider">Parsed Metadata</div>
            <div className="grid grid-cols-2 gap-2 text-slate-300">
              <div><span className="text-slate-500">Method:</span> <span className="font-mono text-rose-400 font-bold">{parsed.method}</span></div>
              <div className="truncate"><span className="text-slate-500">Host:</span> <span className="font-mono text-slate-200">{parsed.url}</span></div>
              <div><span className="text-slate-500">Headers:</span> <span className="font-mono text-indigo-300">{Object.keys(parsed.headers).length}</span></div>
              <div><span className="text-slate-500">Has Body:</span> <span className="font-mono text-emerald-300">{parsed.data ? "Yes" : "No"}</span></div>
            </div>
          </div>
        </div>

        {/* Right: Java Output */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Code2 className="w-4 h-4 text-rose-400" /> Generated Java Code
            </label>
            <button
              onClick={handleCopy}
              className="px-3 py-1 bg-rose-600 hover:bg-rose-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy Java"}
            </button>
          </div>

          <div className="flex flex-wrap items-center gap-4 bg-slate-900/70 p-3 rounded-lg border border-slate-800 text-xs">
            <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={useAsync}
                onChange={(e) => setUseAsync(e.target.checked)}
                className="rounded border-slate-700 bg-slate-800 text-rose-500 focus:ring-0"
              />
              <span>Asynchronous <code className="text-indigo-300">CompletableFuture</code></span>
            </label>
            <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={generateRecord}
                onChange={(e) => setGenerateRecord(e.target.checked)}
                className="rounded border-slate-700 bg-slate-800 text-rose-500 focus:ring-0"
              />
              <span>Generate Java Record DTO</span>
            </label>
          </div>

          <pre className="w-full bg-slate-950/90 font-mono text-xs text-slate-200 border border-slate-800 rounded-xl p-4 overflow-x-auto max-h-[380px] leading-relaxed shadow-inner">
            <code>{javaCode}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}

export default CurlToJavaHttpClientConverter;
