"use client";

import React, { useState, useId } from "react";
import { Copy, Check, Terminal, Code2, Sparkles, RefreshCw } from "lucide-react";

interface ParsedCurl {
  method: string;
  url: string;
  headers: Record<string, string>;
  data?: string;
  hasAuth: boolean;
  authHeader?: string;
}

const SAMPLE_CURLS = [
  {
    name: "POST JSON with Bearer Token",
    command: `curl -X POST "https://api.stripe.com/v1/payment_intents" \\
  -H "Authorization: Bearer sk_test_51MzQ8" \\
  -H "Content-Type: application/json" \\
  -H "Stripe-Version: 2023-10-16" \\
  -d '{"amount":2000,"currency":"usd","payment_method_types":["card"]}'`
  },
  {
    name: "GET with API Key & Headers",
    command: `curl -X GET "https://api.github.com/user/repos?type=owner&sort=updated" \\
  -H "Authorization: Bearer ghp_9381kdk38" \\
  -H "Accept: application/vnd.github.v3+json" \\
  -H "User-Agent: SwiftClient/1.0"`
  },
  {
    name: "PUT Resource with JSON",
    command: `curl -X PUT "https://api.app.io/v1/users/usr_881/preferences" \\
  -H "Content-Type: application/json" \\
  -d '{"notificationsEnabled":true,"theme":"dark"}'`
  }
];

export function CurlToSwiftUrlSessionConverter() {
  const inputId = useId();
  const [curlInput, setCurlInput] = useState(SAMPLE_CURLS[0].command);
  const [useActorPattern, setUseActorPattern] = useState(true);
  const [generateCodable, setGenerateCodable] = useState(true);
  const [copied, setCopied] = useState(false);

  // Parse cURL
  const parseCurl = (cmd: string): ParsedCurl => {
    let method = "GET";
    let url = "";
    const headers: Record<string, string> = {};
    let data: string | undefined = undefined;
    let hasAuth = false;
    let authHeader: string | undefined = undefined;

    const cleanCmd = cmd.replace(/\\\r?\n/g, " ").trim();

    const urlMatch = cleanCmd.match(/(?:https?:\/\/[^\s"']+)/i);
    if (urlMatch) {
      url = urlMatch[0].replace(/["']/g, "");
    }

    const methodMatch = cleanCmd.match(/(?:-X|--request)\s+([A-Z]+)/i);
    if (methodMatch) {
      method = methodMatch[1].toUpperCase();
    } else if (cleanCmd.includes("-d ") || cleanCmd.includes("--data ") || cleanCmd.includes("--data-raw ")) {
      method = "POST";
    }

    const headerRegex = /(?:-H|--header)\s+["']([^"']+)["']/gi;
    let hMatch: RegExpExecArray | null;
    while ((hMatch = headerRegex.exec(cleanCmd)) !== null) {
      const parts = hMatch[1].split(/:\s*/);
      if (parts.length >= 2) {
        const key = parts[0].trim();
        const val = parts.slice(1).join(":").trim();
        headers[key] = val;
        if (key.toLowerCase() === "authorization") {
          hasAuth = true;
          authHeader = val;
        }
      }
    }

    const userMatch = cleanCmd.match(/(?:-u|--user)\s+["']?([^"'\s]+)["']?/i);
    if (userMatch && !hasAuth) {
      hasAuth = true;
      try {
        const b64 = typeof window !== "undefined" ? btoa(userMatch[1]) : Buffer.from(userMatch[1]).toString("base64");
        authHeader = `Basic ${b64}`;
        headers["Authorization"] = authHeader;
      } catch {
        authHeader = "Basic <BASE64>";
        headers["Authorization"] = authHeader;
      }
    }

    const dataMatch = cleanCmd.match(/(?:-d|--data|--data-raw)\s+['"]([^'"]+)['"]/i) ||
                      cleanCmd.match(/(?:-d|--data|--data-raw)\s+([^\s]+)/i);
    if (dataMatch) {
      data = dataMatch[1];
    }

    return { method, url: url || "https://api.example.com/endpoint", headers, data, hasAuth, authHeader };
  };

  const parsed = parseCurl(curlInput);

  // Generate Swift Code
  const generateSwift = (): string => {
    const lines: string[] = [];
    lines.push("// Generated by UTL.tools — cURL to Swift URLSession async/await Converter");
    lines.push("// Modern Swift 5.5+ Concurrency (iOS 15+, macOS 12+)");
    lines.push("import Foundation");
    lines.push("");

    if (useActorPattern) {
      lines.push("actor NetworkClient {");
      lines.push("    static let shared = NetworkClient()");
      lines.push("    private let session: URLSession");
      lines.push("");
      lines.push("    init(configuration: URLSessionConfiguration = .default) {");
      lines.push("        configuration.timeoutIntervalForRequest = 30");
      lines.push("        self.session = URLSession(configuration: configuration)");
      lines.push("    }");
      lines.push("");
      lines.push("    func executeRequest() async throws -> (Data, HTTPURLResponse) {");
    } else {
      lines.push("func executeRequest() async throws -> (Data, HTTPURLResponse) {");
    }

    const indent = useActorPattern ? "        " : "    ";

    lines.push(`${indent}guard let url = URL(string: "${parsed.url}") else {`);
    lines.push(`${indent}    throw URLError(.badURL)`);
    lines.push(`${indent}}`);
    lines.push("");
    lines.push(`${indent}var request = URLRequest(url: url)`);
    lines.push(`${indent}request.httpMethod = "${parsed.method}"`);

    // Headers
    for (const [k, v] of Object.entries(parsed.headers)) {
      lines.push(`${indent}request.setValue("${v}", forHTTPHeaderField: "${k}")`);
    }

    // Body
    if (parsed.data) {
      lines.push("");
      lines.push(`${indent}// Request body payload`);
      try {
        const escapedJson = JSON.stringify(JSON.parse(parsed.data), null, 4);
        lines.push(`${indent}let jsonString = """`);
        lines.push(escapedJson);
        lines.push(`"""`);
        lines.push(`${indent}request.httpBody = jsonString.data(using: .utf8)`);
      } catch {
        const escaped = parsed.data.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        lines.push(`${indent}let rawBody = "${escaped}"`);
        lines.push(`${indent}request.httpBody = rawBody.data(using: .utf8)`);
      }
    }

    lines.push("");
    const sessionCaller = useActorPattern ? "session" : "URLSession.shared";
    lines.push(`${indent}let (data, response) = try await ${sessionCaller}.data(for: request)`);
    lines.push(`${indent}guard let httpResponse = response as? HTTPURLResponse else {`);
    lines.push(`${indent}    throw URLError(.badServerResponse)`);
    lines.push(`${indent}}`);
    lines.push("");
    lines.push(`${indent}guard (200...299).contains(httpResponse.statusCode) else {`);
    lines.push(`${indent}    throw URLError(.init(rawValue: httpResponse.statusCode))`);
    lines.push(`${indent}}`);
    lines.push("");
    lines.push(`${indent}return (data, httpResponse)`);

    if (useActorPattern) {
      lines.push("    }");
      lines.push("}");
    } else {
      lines.push("}");
    }

    // Recommended Codable Model
    if (generateCodable && parsed.data) {
      try {
        const json = JSON.parse(parsed.data);
        if (typeof json === "object" && json !== null && !Array.isArray(json)) {
          lines.push("");
          lines.push("// Suggested Codable DTO struct for this request payload:");
          lines.push("struct RequestPayload: Codable, Sendable {");
          for (const [key, val] of Object.entries(json)) {
            let typeStr = "String";
            if (typeof val === "number") typeStr = Number.isInteger(val) ? "Int" : "Double";
            else if (typeof val === "boolean") typeStr = "Bool";
            else if (Array.isArray(val)) typeStr = "[String]";
            else if (typeof val === "object") typeStr = "[String: String]";

            lines.push(`    let ${key}: ${typeStr}`);
          }
          lines.push("}");
        }
      } catch {}
    }

    return lines.join("\n");
  };

  const swiftCode = generateSwift();

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(swiftCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-slate-200">
      {/* Header */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-6 shadow-xl backdrop-blur-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/20">
                Swift 5.5+ / iOS 15+ / macOS 12+
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                URLSession async/await Concurrency
              </span>
            </div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              <Terminal className="w-6 h-6 text-amber-400" />
              cURL to Swift URLSession async/await Converter
            </h1>
            <p className="text-slate-400 text-sm mt-1">
              Convert raw cURL terminal commands into modern, thread-safe Swift networking code using <code className="text-amber-300">URLSession.shared.data(for:)</code>, structured concurrency, and <code className="text-amber-300">Codable</code> structs.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            {SAMPLE_CURLS.map((sample, idx) => (
              <button
                key={idx}
                onClick={() => setCurlInput(sample.command)}
                className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-xs font-medium text-slate-300 rounded-lg border border-slate-700 transition"
              >
                {sample.name}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Input */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label htmlFor={inputId} className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-amber-400" /> Input cURL Command
            </label>
            <button
              onClick={() => setCurlInput("")}
              className="text-xs text-slate-400 hover:text-slate-200 flex items-center gap-1 transition"
            >
              <RefreshCw className="w-3 h-3" /> Clear
            </button>
          </div>
          <textarea
            id={inputId}
            value={curlInput}
            onChange={(e) => setCurlInput(e.target.value)}
            rows={14}
            className="w-full bg-slate-950/90 font-mono text-xs text-amber-300 border border-slate-800 rounded-xl p-4 focus:ring-2 focus:ring-amber-500/40 focus:border-amber-500/50 outline-none resize-y leading-relaxed shadow-inner"
          />

          <div className="bg-slate-900/60 border border-slate-800/80 rounded-xl p-4 text-xs space-y-2">
            <div className="text-slate-400 font-semibold text-[11px] uppercase tracking-wider">Parsed Metadata</div>
            <div className="grid grid-cols-2 gap-2 text-slate-300">
              <div><span className="text-slate-500">Method:</span> <span className="font-mono text-amber-400 font-bold">{parsed.method}</span></div>
              <div className="truncate"><span className="text-slate-500">Host:</span> <span className="font-mono text-slate-200">{parsed.url}</span></div>
              <div><span className="text-slate-500">Headers:</span> <span className="font-mono text-indigo-300">{Object.keys(parsed.headers).length}</span></div>
              <div><span className="text-slate-500">Has Body:</span> <span className="font-mono text-emerald-300">{parsed.data ? "Yes" : "No"}</span></div>
            </div>
          </div>
        </div>

        {/* Right: Swift Output */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Code2 className="w-4 h-4 text-amber-400" /> Generated Swift Code
            </label>
            <button
              onClick={handleCopy}
              className="px-3 py-1 bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy Swift"}
            </button>
          </div>

          <div className="flex flex-wrap items-center gap-4 bg-slate-900/70 p-3 rounded-lg border border-slate-800 text-xs">
            <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={useActorPattern}
                onChange={(e) => setUseActorPattern(e.target.checked)}
                className="rounded border-slate-700 bg-slate-800 text-amber-500 focus:ring-0"
              />
              <span>Thread-Safe <code className="text-amber-300">actor</code> Pattern</span>
            </label>
            <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={generateCodable}
                onChange={(e) => setGenerateCodable(e.target.checked)}
                className="rounded border-slate-700 bg-slate-800 text-amber-500 focus:ring-0"
              />
              <span>Generate <code className="text-amber-300">Codable</code> Struct</span>
            </label>
          </div>

          <pre className="w-full bg-slate-950/90 font-mono text-xs text-slate-200 border border-slate-800 rounded-xl p-4 overflow-x-auto max-h-[380px] leading-relaxed shadow-inner">
            <code>{swiftCode}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}

export default CurlToSwiftUrlSessionConverter;
