"use client";

import React, { useState, useId } from "react";
import { Copy, Check, Terminal, Code2, Sparkles, RefreshCw } from "lucide-react";

interface ParsedCurl {
  method: string;
  url: string;
  headers: Record<string, string>;
  data?: string;
  hasAuth: boolean;
  authHeader?: string;
}

const SAMPLE_CURLS = [
  {
    name: "POST JSON with Bearer Token",
    command: `curl -X POST "https://api.example.com/v1/customers" \\
  -H "Authorization: Bearer sec_live_9f83ac92b81" \\
  -H "Content-Type: application/json" \\
  -H "X-Client-Version: 2.4.0" \\
  -d '{"name":"Acme Global","email":"ops@acme.corp","plan":"enterprise","seats":45}'`
  },
  {
    name: "GET with Query Parameters & API Key",
    command: `curl -X GET "https://api.weather.io/v2/forecast?lat=37.7749&lon=-122.4194&units=metric" \\
  -H "X-Api-Key: wthr_live_key_99812" \\
  -H "Accept: application/json"`
  },
  {
    name: "PUT Resource with Basic Auth",
    command: `curl -X PUT "https://service.domain.net/api/v1/tenants/t-8812/settings" \\
  -u "admin_svc:K9#mQx$28L" \\
  -H "Content-Type: application/json" \\
  -d '{"maintenanceMode":false,"tier":"premium"}'`
  }
];

export function CurlToCSharpHttpClientConverter() {
  const inputId = useId();
  const [curlInput, setCurlInput] = useState(SAMPLE_CURLS[0].command);
  const [useHttpClientFactory, setUseHttpClientFactory] = useState(true);
  const [generateRecordDto, setGenerateRecordDto] = useState(true);
  const [copied, setCopied] = useState(false);

  // Parse cURL
  const parseCurl = (cmd: string): ParsedCurl => {
    let method = "GET";
    let url = "";
    const headers: Record<string, string> = {};
    let data: string | undefined = undefined;
    let hasAuth = false;
    let authHeader: string | undefined = undefined;

    // Normalize command by stripping trailing backslashes and carriage returns
    const cleanCmd = cmd.replace(/\\\r?\n/g, " ").trim();

    // Match URL: look for quotes or space-separated URL
    const urlMatch = cleanCmd.match(/(?:https?:\/\/[^\s"']+)/i);
    if (urlMatch) {
      url = urlMatch[0].replace(/["']/g, "");
    }

    // Match explicit method -X or --request
    const methodMatch = cleanCmd.match(/(?:-X|--request)\s+([A-Z]+)/i);
    if (methodMatch) {
      method = methodMatch[1].toUpperCase();
    } else if (cleanCmd.includes("-d ") || cleanCmd.includes("--data ") || cleanCmd.includes("--data-raw ")) {
      method = "POST";
    }

    // Match headers -H or --header
    const headerRegex = /(?:-H|--header)\s+["']([^"']+)["']/gi;
    let hMatch: RegExpExecArray | null;
    while ((hMatch = headerRegex.exec(cleanCmd)) !== null) {
      const parts = hMatch[1].split(/:\s*/);
      if (parts.length >= 2) {
        const key = parts[0].trim();
        const val = parts.slice(1).join(":").trim();
        headers[key] = val;
        if (key.toLowerCase() === "authorization") {
          hasAuth = true;
          authHeader = val;
        }
      }
    }

    // Match Basic Auth -u or --user
    const userMatch = cleanCmd.match(/(?:-u|--user)\s+["']?([^"'\s]+)["']?/i);
    if (userMatch && !hasAuth) {
      hasAuth = true;
      try {
        const b64 = typeof window !== "undefined" ? btoa(userMatch[1]) : Buffer.from(userMatch[1]).toString("base64");
        authHeader = `Basic ${b64}`;
        headers["Authorization"] = authHeader;
      } catch {
        authHeader = `Basic <BASE64_AUTH>`;
        headers["Authorization"] = authHeader;
      }
    }

    // Match payload -d, --data, --data-raw
    const dataMatch = cleanCmd.match(/(?:-d|--data|--data-raw)\s+['"]([^'"]+)['"]/i) ||
                      cleanCmd.match(/(?:-d|--data|--data-raw)\s+([^\s]+)/i);
    if (dataMatch) {
      data = dataMatch[1];
    }

    return { method, url: url || "https://api.example.com/endpoint", headers, data, hasAuth, authHeader };
  };

  const parsed = parseCurl(curlInput);

  // Generate C# Code
  const generateCSharp = (): string => {
    const lines: string[] = [];
    lines.push("// Generated by UTL.tools — cURL to C# .NET HttpClient Converter");
    lines.push("// Zero external packages required; uses native System.Net.Http and System.Text.Json");
    lines.push("using System;");
    lines.push("using System.Net.Http;");
    lines.push("using System.Net.Http.Headers;");
    lines.push("using System.Text;");
    lines.push("using System.Text.Json;");
    lines.push("using System.Threading;");
    lines.push("using System.Threading.Tasks;");
    lines.push("");

    if (useHttpClientFactory) {
      lines.push("public class ApiClientService");
      lines.push("{");
      lines.push("    private readonly IHttpClientFactory _httpClientFactory;");
      lines.push("");
      lines.push("    public ApiClientService(IHttpClientFactory httpClientFactory)");
      lines.push("    {");
      lines.push("        _httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));");
      lines.push("    }");
      lines.push("");
      lines.push("    public async Task<string> ExecuteRequestAsync(CancellationToken cancellationToken = default)");
      lines.push("    {");
      lines.push("        var client = _httpClientFactory.CreateClient();");
      lines.push("        client.Timeout = TimeSpan.FromSeconds(30);");
    } else {
      lines.push("public static class ApiClient");
      lines.push("{");
      lines.push("    // In production, instantiate HttpClient once per application lifecycle or use IHttpClientFactory");
      lines.push("    private static readonly HttpClient client = new HttpClient");
      lines.push("    {");
      lines.push("        Timeout = TimeSpan.FromSeconds(30)");
      lines.push("    };");
      lines.push("");
      lines.push("    public static async Task<string> ExecuteRequestAsync(CancellationToken cancellationToken = default)");
      lines.push("    {");
    }

    const indent = "        ";

    // Setup request message
    lines.push(`${indent}using var request = new HttpRequestMessage(HttpMethod.${parsed.method.charAt(0) + parsed.method.slice(1).toLowerCase()}, "${parsed.url}");`);

    // Headers
    const nonContentHeaders: [string, string][] = [];
    let contentType = "application/json";

    for (const [k, v] of Object.entries(parsed.headers)) {
      if (k.toLowerCase() === "content-type") {
        contentType = v;
      } else if (k.toLowerCase() === "authorization") {
        const parts = v.split(" ");
        if (parts.length === 2) {
          lines.push(`${indent}request.Headers.Authorization = new AuthenticationHeaderValue("${parts[0]}", "${parts[1]}");`);
        } else {
          lines.push(`${indent}request.Headers.TryAddWithoutValidation("Authorization", "${v}");`);
        }
      } else {
        nonContentHeaders.push([k, v]);
      }
    }

    for (const [k, v] of nonContentHeaders) {
      lines.push(`${indent}request.Headers.TryAddWithoutValidation("${k}", "${v}");`);
    }

    // Body if present
    if (parsed.data) {
      try {
        lines.push("");
        lines.push(`${indent}// Raw payload`);
        lines.push(`${indent}var jsonPayload = @"""`);
        lines.push(JSON.stringify(JSON.parse(parsed.data), null, 4));
        lines.push(`""";`);
        lines.push(`${indent}request.Content = new StringContent(jsonPayload, Encoding.UTF8, "${contentType}");`);
      } catch {
        const escaped = parsed.data.replace(/"/g, '""');
        lines.push(`${indent}request.Content = new StringContent(@"""${escaped}""", Encoding.UTF8, "${contentType}");`);
      }
    }

    lines.push("");
    lines.push(`${indent}using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);`);
    lines.push(`${indent}response.EnsureSuccessStatusCode();`);
    lines.push("");
    lines.push(`${indent}var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);`);
    lines.push(`${indent}return responseBody;`);
    lines.push("    }");
    lines.push("}");

    // Add Record DTO recommendation if JSON body exists
    if (generateRecordDto && parsed.data) {
      try {
        const parsedJson = JSON.parse(parsed.data);
        if (typeof parsedJson === "object" && parsedJson !== null && !Array.isArray(parsedJson)) {
          lines.push("");
          lines.push("// Suggested strongly-typed C# record DTO for this payload:");
          lines.push("public sealed record RequestPayload(");
          const entries = Object.entries(parsedJson);
          entries.forEach(([key, val], idx) => {
            let typeStr = "string";
            if (typeof val === "number") typeStr = Number.isInteger(val) ? "int" : "double";
            else if (typeof val === "boolean") typeStr = "bool";
            else if (Array.isArray(val)) typeStr = "List<object>";
            else if (typeof val === "object") typeStr = "object";
            const pascalKey = key.charAt(0).toUpperCase() + key.slice(1);
            const comma = idx === entries.length - 1 ? "" : ",";
            lines.push(`    ${typeStr} ${pascalKey}${comma}`);
          });
          lines.push(");");
        }
      } catch {
        // Ignored if not JSON
      }
    }

    return lines.join("\n");
  };

  const csharpCode = generateCSharp();

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(csharpCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-slate-200">
      {/* Hero Header */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-6 shadow-xl backdrop-blur-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                .NET 8 / .NET 9 Ready
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                Zero-Alloc Native HttpClient
              </span>
            </div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              <Terminal className="w-6 h-6 text-emerald-400" />
              cURL to C# / .NET HttpClient Converter
            </h1>
            <p className="text-slate-400 text-sm mt-1">
              Transform raw cURL CLI requests into production-ready C# code utilizing <code className="text-emerald-300">HttpRequestMessage</code>, <code className="text-emerald-300">IHttpClientFactory</code> dependency injection, and strongly-typed JSON DTO records.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            {SAMPLE_CURLS.map((sample, idx) => (
              <button
                key={idx}
                onClick={() => setCurlInput(sample.command)}
                className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-xs font-medium text-slate-300 rounded-lg border border-slate-700 transition"
              >
                {sample.name}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Editor Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: cURL Input */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label htmlFor={inputId} className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-emerald-400" />
              Input cURL Command
            </label>
            <button
              onClick={() => setCurlInput("")}
              className="text-xs text-slate-400 hover:text-slate-200 flex items-center gap-1 transition"
            >
              <RefreshCw className="w-3 h-3" /> Clear
            </button>
          </div>
          <textarea
            id={inputId}
            value={curlInput}
            onChange={(e) => setCurlInput(e.target.value)}
            placeholder="curl -X POST https://api.example.com ... -H '...' -d '{...}'"
            rows={14}
            className="w-full bg-slate-950/90 font-mono text-xs text-emerald-300 border border-slate-800 rounded-xl p-4 focus:ring-2 focus:ring-emerald-500/40 focus:border-emerald-500/50 outline-none resize-y leading-relaxed shadow-inner"
          />

          {/* Parsed Inspection Card */}
          <div className="bg-slate-900/60 border border-slate-800/80 rounded-xl p-4 text-xs space-y-2">
            <div className="text-slate-400 font-semibold text-[11px] uppercase tracking-wider">Parsed Metadata</div>
            <div className="grid grid-cols-2 gap-2 text-slate-300">
              <div><span className="text-slate-500">Method:</span> <span className="font-mono text-emerald-400 font-bold">{parsed.method}</span></div>
              <div className="truncate"><span className="text-slate-500">Host:</span> <span className="font-mono text-slate-200">{parsed.url}</span></div>
              <div><span className="text-slate-500">Headers:</span> <span className="font-mono text-indigo-300">{Object.keys(parsed.headers).length}</span></div>
              <div><span className="text-slate-500">Has Body:</span> <span className="font-mono text-amber-300">{parsed.data ? "Yes" : "No"}</span></div>
            </div>
          </div>
        </div>

        {/* Right: C# Output */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Code2 className="w-4 h-4 text-indigo-400" />
              Generated C# Code
            </label>
            <div className="flex items-center gap-3">
              <button
                onClick={handleCopy}
                className="px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied!" : "Copy C#"}
              </button>
            </div>
          </div>

          {/* Code options */}
          <div className="flex flex-wrap items-center gap-4 bg-slate-900/70 p-3 rounded-lg border border-slate-800 text-xs">
            <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={useHttpClientFactory}
                onChange={(e) => setUseHttpClientFactory(e.target.checked)}
                className="rounded border-slate-700 bg-slate-800 text-emerald-500 focus:ring-0"
              />
              <span>Use <code className="text-indigo-300">IHttpClientFactory</code> Pattern</span>
            </label>
            <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
              <input
                type="checkbox"
                checked={generateRecordDto}
                onChange={(e) => setGenerateRecordDto(e.target.checked)}
                className="rounded border-slate-700 bg-slate-800 text-emerald-500 focus:ring-0"
              />
              <span>Generate DTO Record</span>
            </label>
          </div>

          <pre className="w-full bg-slate-950/90 font-mono text-xs text-slate-200 border border-slate-800 rounded-xl p-4 overflow-x-auto max-h-[380px] leading-relaxed shadow-inner">
            <code>{csharpCode}</code>
          </pre>
        </div>
      </div>

      {/* Engineering Reference Notes */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs text-slate-400 pt-2">
        <div className="bg-slate-900/60 p-4 rounded-xl border border-slate-800/80">
          <div className="text-emerald-400 font-semibold mb-1 flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" /> Socket Exhaustion Prevention
          </div>
          Using <code className="text-slate-300">IHttpClientFactory</code> or a long-lived static <code className="text-slate-300">HttpClient</code> avoids socket exhaustion under heavy load, delegating connection pool rotation to <code className="text-slate-300">SocketsHttpHandler</code>.
        </div>
        <div className="bg-slate-900/60 p-4 rounded-xl border border-slate-800/80">
          <div className="text-indigo-400 font-semibold mb-1">
            Raw String Literals
          </div>
          Generates modern C# 11+ raw string multi-line literals to cleanly embed raw JSON strings without tedious quote escaping.
        </div>
        <div className="bg-slate-900/60 p-4 rounded-xl border border-slate-800/80">
          <div className="text-amber-400 font-semibold mb-1">
            Cancellation & Streaming
          </div>
          Employs <code className="text-slate-300">HttpCompletionOption.ResponseHeadersRead</code> and <code className="text-slate-300">CancellationToken</code> for optimal memory efficiency and responsive timeout handling.
        </div>
      </div>
    </div>
  );
}

export default CurlToCSharpHttpClientConverter;
